controller_manager:
  ros__parameters:
    # update_rate: 100  # Hz
    use_sim_time: true
    
    # Controller names
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# Joint State Broadcaster configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - dof_wheel_bl
      - dof_wheel_br
      - dof_holder_fl
      - dof_holder_fr
      - dof_wheel_holder_fl
      - dof_wheel_holder_fr

# Ackermann Steering Controller configuration
ackermann_steering_controller:
  ros__parameters:
    # Reference frame for the controller
    reference_timeout: 0.5
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true
    
    # Wheel separation and wheelbase
    wheel_separation: 0.26  # Distance between left and right wheels (2 * 0.13)
    wheelbase: 0.6  # Distance between front and rear axles (0.30003964 + 0.29996036)
    wheel_radius: 0.05    # Joint names

    front_wheels_names: 
      - dof_wheel_holder_fl
      - dof_wheel_holder_fr
    rear_wheels_names:
      - dof_wheel_bl  
      - dof_wheel_br
    front_wheels_state_names:
      - dof_wheel_holder_fl
      - dof_wheel_holder_fr
    rear_wheels_state_names:
      - dof_wheel_bl
      - dof_wheel_br
    front_steering_names:
      - dof_holder_fl
      - dof_holder_fr
      
    # Command interfaces
    front_wheels_command_interfaces:
      - velocity
    rear_wheels_command_interfaces: 
      - velocity
    front_steering_command_interfaces:
      - position
      
    # State interfaces  
    front_wheels_state_interfaces:
      - position
      - velocity
    rear_wheels_state_interfaces:
      - position  
      - velocity
    front_steering_state_interfaces:
      - position
      - velocity
      
    # Twist command topic
    reference_timeout: 0.5
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    publish_wheel_data: true
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 2.0  # m/s
        max_acceleration: 1.0  # m/s^2
        min_velocity: -2.0  # m/s
        min_acceleration: -1.0  # m/s^2
        has_jerk_limits: false
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true  
        max_velocity: 1.0  # rad/s
        max_acceleration: 1.0  # rad/s^2
        min_velocity: -1.0  # rad/s
        min_acceleration: -1.0  # rad/s^2
        has_jerk_limits: false